language: python
python:
  - 2.7

sudo: required
dist: trusty

notifications:
  slack: silab-bonn:nU3pnaHN3RJ6WRFrfjec9vPM
  email:
    - hemperek@uni-bonn.de
    - janssen@physik.uni-bonn.de
    - pohl@physik.uni-bonn.de

before_install:
  # Install cocotb and iverilog for interface test
#  - git clone https://github.com/potentialventures/cocotb
#  - export COCOTB=$(pwd)/cocotb
  # Build iverilog from source
  - sudo apt-get install gperf
  - git clone https://github.com/steveicarus/iverilog.git
  - cd iverilog && autoconf && ./configure && make && sudo make install && cd ..
  # Download iverilog from PPA
#  - sudo add-apt-repository -y ppa:team-electronics/ppa
#  - sudo apt-get -q update
#  - sudo apt-get -q install iverilog-daily
  # Download iverilog from conda-forge
#  - conda config --add channels conda-forge
#  - conda install iverilog

install:
  # conda
  - wget http://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda
  - conda update --yes --all
  - conda info -a
  - conda create --yes -n test-environment python=$TRAVIS_PYTHON_VERSION numpy bitarray nose pyyaml coverage
  - source activate test-environment
  - pip install pyvisa pyvisa-sim coveralls cocotb
  # install basil
  - python setup.py develop

script:
  - nosetests --with-coverage --cover-package=basil  tests/test_*.py examples/*/*/test_*.py

after_success:
  - coveralls

deploy:
  provider: pypi
  user: DavidLP
  password:
    secure: EOfeXP4oyoNLY8Ot2/pX3k2Acvk5Xn0VkBeqXHND/rjm4iveUGrLbMDOffDnvkFgSYQ6PO/UqZjSb8vPd5nQ1Uhw8YyEhXUTPVWOz7ebq/xOmI8DIpFQH24/u7K3D9ygm7mlN3ozz9/6Gvk2VXk8OUT8csMtIJ586FnNBFdq0XVXzneHx6Ppr4GvAvh5Li5dd0ZqL1Cd2JZZyhWbQzidJgBkU1NOD7pRmEPh7dfG23rOEuzHQPyip8PKw86ErbjRD6WevjyFsetT66je3G8+ZSvJIDNVQ95oohhBZ7bRA+VwHnt2MdWxBYSAq7ZxbNmcs5LsvuNiJRyGo9Iue97yKI/EX0GzK/mA0pO/kdu0n1BzXxVePtxBOxLgzmEKs2S0IV45zdlAIfOjs7gLM8mHjiFC6oFuDddKPp5dYRMpOERt3jfQVBbSWpGkN4tcwXZ/1xMm1IxTaU06YQMLKtRqo2N5k9aWMSsvFfagQ44WW658ra/15TdaZyniBCiYQ0a3NDYEpjZX4n4Sh0JDcGqlyOJcpcq+gl2NaIADX+X6Qoe6C7s036LowfoTDh83X72hjvm8smrdGL1op7DQo3dGxwU6FRvf78Qw528v2CkrdTHzIOr5IEuZkh+xGiGJE2UDTwHdq/nAr+O79s2yAakvf/DL/s8ZU+MvZ21dobtnLAg=
  on:
    tags: true
    repo: SiLab-Bonn/basil
  distributions: "sdist bdist_wheel"
