language: python
python:
  - 2.7
  
sudo: required
dist: trusty

notifications:
  email:
    - hemperek@uni-bonn.de
    - janssen@physik.uni-bonn.de
    - pohl@physik.uni-bonn.de

before_install:
  - sudo add-apt-repository -y ppa:team-electronics/ppa
  - sudo apt-get update

install:
   
  #conda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda update --yes conda
  - conda install --yes numpy bitarray nose pyyaml
  - pip install pyvisa pyvisa-sim
  
  #cocotb
  - git clone https://github.com/potentialventures/cocotb.git
  - export COCOTB=$(pwd)/cocotb
 
  #iverilog
  - sudo apt-get -y install iverilog-daily  

  # Install basil
  - python setup.py develop

script:
  - nosetests tests/test_*.py examples/MIO/tb/test_*.py examples/mio_sram_test/tests/test_*.py examples/mio_pixel/tests/test_*.py 
